"""change user to username

Revision ID: f2499b856e5f
Revises: 6cb5468f3f75
Create Date: 2025-06-06 09:53:42.380012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2499b856e5f'
down_revision = '6cb5468f3f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
